id: I184F7DB0
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T16:24:33+00:00'
last_modified: '2022-06-08T12:46:00.316902+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2353
  title: ཀླུ་འབུམ་དཀར་ནག་ཁྲ་གསུམ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    39E2:
      image_group_id: I3CN2355
      title: ''
      total_pages: 227
      order: 1
      base_file: 39E2.txt
    D878:
      image_group_id: I3CN2356
      title: ''
      total_pages: 634
      order: 2
      base_file: D878.txt
    FC41:
      image_group_id: I3CN2357
      title: ''
      total_pages: 626
      order: 3
      base_file: FC41.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
