id: P010326
initial_creation_type: ocr
created_at: 21/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W3CN2353
  title: ཀླུ་འབུམ་དཀར་ནག་ཁྲ་གསུམ།
  author: ''
  volumes:
    6d5ac20df51049ceb7189471fbd61500:
      image_group_id: I3CN2355
      title: ''
      volume_number: 1
      total_pages: 227
      base_file: v001.txt
    06eee572d1f647eb8815ad8d87ed1283:
      image_group_id: I3CN2356
      title: ''
      volume_number: 2
      total_pages: 634
      base_file: v002.txt
    6549567915ec4bb4942072ff8d3078c8:
      image_group_id: I3CN2357
      title: ''
      volume_number: 3
      total_pages: 626
      base_file: v003.txt
